/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "rca_64bit.v:35" *)
module four_0bit(a, b, sum4, cout4);
  (* src = "rca_64bit.v:36" *)
  input [3:0] a;
  (* src = "rca_64bit.v:36" *)
  input [3:0] b;
  (* src = "rca_64bit.v:38" *)
  output cout4;
  (* src = "rca_64bit.v:39" *)
  wire [2:0] r;
  (* src = "rca_64bit.v:37" *)
  output [3:0] sum4;
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:42" *)
  full_adder ffa1 (
    .a(a[1]),
    .b(b[1]),
    .cin(r[0]),
    .cout2(r[1]),
    .sum2(sum4[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:43" *)
  full_adder ffa2 (
    .a(a[2]),
    .b(b[2]),
    .cin(r[1]),
    .cout2(r[2]),
    .sum2(sum4[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:44" *)
  full_adder ffa3 (
    .a(a[3]),
    .b(b[3]),
    .cin(r[2]),
    .cout2(cout4),
    .sum2(sum4[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:41" *)
  half_adder ha1 (
    .a(a[0]),
    .b(b[0]),
    .cout1(r[0]),
    .sum1(sum4[0])
  );
endmodule

(* src = "rca_64bit.v:21" *)
module four_1bit(a, b, sum3, cout3, cin);
  (* src = "rca_64bit.v:22" *)
  input [3:0] a;
  (* src = "rca_64bit.v:22" *)
  input [3:0] b;
  (* src = "rca_64bit.v:23" *)
  input cin;
  (* src = "rca_64bit.v:25" *)
  output cout3;
  (* src = "rca_64bit.v:26" *)
  wire [2:0] r;
  (* src = "rca_64bit.v:24" *)
  output [3:0] sum3;
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:28" *)
  full_adder fa1 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout2(r[0]),
    .sum2(sum3[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:29" *)
  full_adder fa2 (
    .a(a[1]),
    .b(b[1]),
    .cin(r[0]),
    .cout2(r[1]),
    .sum2(sum3[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:30" *)
  full_adder fa3 (
    .a(a[2]),
    .b(b[2]),
    .cin(r[1]),
    .cout2(r[2]),
    .sum2(sum3[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:31" *)
  full_adder fa4 (
    .a(a[3]),
    .b(b[3]),
    .cin(r[2]),
    .cout2(cout3),
    .sum2(sum3[3])
  );
endmodule

(* src = "rca_64bit.v:11" *)
module full_adder(a, b, sum2, cout2, cin);
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "rca_64bit.v:12" *)
  wire _03_;
  (* src = "rca_64bit.v:12" *)
  wire _04_;
  (* src = "rca_64bit.v:12" *)
  wire _05_;
  (* src = "rca_64bit.v:13" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "rca_64bit.v:13" *)
  wire _10_;
  (* src = "rca_64bit.v:12" *)
  input a;
  (* src = "rca_64bit.v:12" *)
  input b;
  (* src = "rca_64bit.v:12" *)
  input cin;
  (* src = "rca_64bit.v:13" *)
  output cout2;
  (* src = "rca_64bit.v:13" *)
  output sum2;
  INV_X1 _11_ (
    .A(_05_),
    .ZN(_07_)
  );
  NAND2_X1 _12_ (
    .A1(_04_),
    .A2(_03_),
    .ZN(_08_)
  );
  XNOR2_X1 _13_ (
    .A(_04_),
    .B(_03_),
    .ZN(_09_)
  );
  XNOR2_X1 _14_ (
    .A(_05_),
    .B(_09_),
    .ZN(_10_)
  );
  OAI21_X1 _15_ (
    .A(_08_),
    .B1(_09_),
    .B2(_07_),
    .ZN(_06_)
  );
  assign _05_ = cin;
  assign _04_ = b;
  assign _03_ = a;
  assign sum2 = _10_;
  assign cout2 = _06_;
endmodule

(* src = "rca_64bit.v:2" *)
module half_adder(a, b, sum1, cout1);
  (* src = "rca_64bit.v:3" *)
  wire _0_;
  (* src = "rca_64bit.v:3" *)
  wire _1_;
  (* src = "rca_64bit.v:4" *)
  wire _2_;
  (* src = "rca_64bit.v:4" *)
  wire _3_;
  (* src = "rca_64bit.v:3" *)
  input a;
  (* src = "rca_64bit.v:3" *)
  input b;
  (* src = "rca_64bit.v:4" *)
  output cout1;
  (* src = "rca_64bit.v:4" *)
  output sum1;
  AND2_X1 _4_ (
    .A1(_1_),
    .A2(_0_),
    .ZN(_2_)
  );
  XOR2_X1 _5_ (
    .A(_1_),
    .B(_0_),
    .Z(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum1 = _3_;
  assign cout1 = _2_;
endmodule

(* top =  1  *)
(* src = "rca_64bit.v:48" *)
module rca_64bit(op1, op2, sum, crout, reset, clock);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  (* src = "rca_64bit.v:55" *)
  wire [63:0] a;
  (* src = "rca_64bit.v:55" *)
  wire [63:0] b;
  (* src = "rca_64bit.v:50" *)
  input clock;
  (* src = "rca_64bit.v:56" *)
  wire coutf;
  (* src = "rca_64bit.v:53" *)
  output crout;
  (* src = "rca_64bit.v:49" *)
  input [63:0] op1;
  (* src = "rca_64bit.v:49" *)
  input [63:0] op2;
  (* src = "rca_64bit.v:54" *)
  wire [14:0] r;
  (* src = "rca_64bit.v:50" *)
  input reset;
  (* src = "rca_64bit.v:51" *)
  output [63:0] sum;
  (* src = "rca_64bit.v:52" *)
  wire [63:0] sumf;
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _193_ (
    .CK(clock),
    .D(op1[33]),
    .Q(a[33]),
    .QN(_000_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _194_ (
    .CK(clock),
    .D(op1[34]),
    .Q(a[34]),
    .QN(_001_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _195_ (
    .CK(clock),
    .D(op1[35]),
    .Q(a[35]),
    .QN(_002_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _196_ (
    .CK(clock),
    .D(op1[36]),
    .Q(a[36]),
    .QN(_003_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _197_ (
    .CK(clock),
    .D(op1[37]),
    .Q(a[37]),
    .QN(_004_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _198_ (
    .CK(clock),
    .D(op1[38]),
    .Q(a[38]),
    .QN(_005_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _199_ (
    .CK(clock),
    .D(op1[39]),
    .Q(a[39]),
    .QN(_006_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _200_ (
    .CK(clock),
    .D(op1[40]),
    .Q(a[40]),
    .QN(_007_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _201_ (
    .CK(clock),
    .D(op1[41]),
    .Q(a[41]),
    .QN(_008_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _202_ (
    .CK(clock),
    .D(op1[42]),
    .Q(a[42]),
    .QN(_009_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _203_ (
    .CK(clock),
    .D(op1[43]),
    .Q(a[43]),
    .QN(_010_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _204_ (
    .CK(clock),
    .D(op1[44]),
    .Q(a[44]),
    .QN(_011_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _205_ (
    .CK(clock),
    .D(op1[45]),
    .Q(a[45]),
    .QN(_012_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _206_ (
    .CK(clock),
    .D(op1[46]),
    .Q(a[46]),
    .QN(_013_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _207_ (
    .CK(clock),
    .D(op1[47]),
    .Q(a[47]),
    .QN(_014_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _208_ (
    .CK(clock),
    .D(op1[48]),
    .Q(a[48]),
    .QN(_015_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _209_ (
    .CK(clock),
    .D(op1[49]),
    .Q(a[49]),
    .QN(_016_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _210_ (
    .CK(clock),
    .D(op1[50]),
    .Q(a[50]),
    .QN(_017_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _211_ (
    .CK(clock),
    .D(op1[51]),
    .Q(a[51]),
    .QN(_018_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _212_ (
    .CK(clock),
    .D(op1[52]),
    .Q(a[52]),
    .QN(_019_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _213_ (
    .CK(clock),
    .D(op1[53]),
    .Q(a[53]),
    .QN(_020_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _214_ (
    .CK(clock),
    .D(op1[54]),
    .Q(a[54]),
    .QN(_021_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _215_ (
    .CK(clock),
    .D(op1[55]),
    .Q(a[55]),
    .QN(_022_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _216_ (
    .CK(clock),
    .D(op1[56]),
    .Q(a[56]),
    .QN(_023_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _217_ (
    .CK(clock),
    .D(op1[57]),
    .Q(a[57]),
    .QN(_024_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _218_ (
    .CK(clock),
    .D(op1[58]),
    .Q(a[58]),
    .QN(_025_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _219_ (
    .CK(clock),
    .D(op1[59]),
    .Q(a[59]),
    .QN(_026_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _220_ (
    .CK(clock),
    .D(op1[60]),
    .Q(a[60]),
    .QN(_027_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _221_ (
    .CK(clock),
    .D(op1[61]),
    .Q(a[61]),
    .QN(_028_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _222_ (
    .CK(clock),
    .D(op1[62]),
    .Q(a[62]),
    .QN(_029_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _223_ (
    .CK(clock),
    .D(op1[63]),
    .Q(a[63]),
    .QN(_030_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _224_ (
    .CK(clock),
    .D(sumf[0]),
    .Q(sum[0]),
    .QN(_031_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _225_ (
    .CK(clock),
    .D(sumf[1]),
    .Q(sum[1]),
    .QN(_032_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _226_ (
    .CK(clock),
    .D(sumf[2]),
    .Q(sum[2]),
    .QN(_033_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _227_ (
    .CK(clock),
    .D(sumf[3]),
    .Q(sum[3]),
    .QN(_034_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _228_ (
    .CK(clock),
    .D(sumf[4]),
    .Q(sum[4]),
    .QN(_035_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _229_ (
    .CK(clock),
    .D(sumf[5]),
    .Q(sum[5]),
    .QN(_036_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _230_ (
    .CK(clock),
    .D(sumf[6]),
    .Q(sum[6]),
    .QN(_037_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _231_ (
    .CK(clock),
    .D(sumf[7]),
    .Q(sum[7]),
    .QN(_038_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _232_ (
    .CK(clock),
    .D(sumf[8]),
    .Q(sum[8]),
    .QN(_039_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _233_ (
    .CK(clock),
    .D(sumf[9]),
    .Q(sum[9]),
    .QN(_040_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _234_ (
    .CK(clock),
    .D(sumf[10]),
    .Q(sum[10]),
    .QN(_041_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _235_ (
    .CK(clock),
    .D(sumf[11]),
    .Q(sum[11]),
    .QN(_042_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _236_ (
    .CK(clock),
    .D(sumf[12]),
    .Q(sum[12]),
    .QN(_043_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _237_ (
    .CK(clock),
    .D(sumf[13]),
    .Q(sum[13]),
    .QN(_044_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _238_ (
    .CK(clock),
    .D(sumf[14]),
    .Q(sum[14]),
    .QN(_045_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _239_ (
    .CK(clock),
    .D(sumf[15]),
    .Q(sum[15]),
    .QN(_046_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _240_ (
    .CK(clock),
    .D(sumf[16]),
    .Q(sum[16]),
    .QN(_047_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _241_ (
    .CK(clock),
    .D(sumf[17]),
    .Q(sum[17]),
    .QN(_048_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _242_ (
    .CK(clock),
    .D(sumf[18]),
    .Q(sum[18]),
    .QN(_049_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _243_ (
    .CK(clock),
    .D(sumf[19]),
    .Q(sum[19]),
    .QN(_050_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _244_ (
    .CK(clock),
    .D(sumf[20]),
    .Q(sum[20]),
    .QN(_051_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _245_ (
    .CK(clock),
    .D(sumf[21]),
    .Q(sum[21]),
    .QN(_052_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _246_ (
    .CK(clock),
    .D(sumf[22]),
    .Q(sum[22]),
    .QN(_053_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _247_ (
    .CK(clock),
    .D(sumf[23]),
    .Q(sum[23]),
    .QN(_054_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _248_ (
    .CK(clock),
    .D(sumf[24]),
    .Q(sum[24]),
    .QN(_055_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _249_ (
    .CK(clock),
    .D(sumf[25]),
    .Q(sum[25]),
    .QN(_056_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _250_ (
    .CK(clock),
    .D(sumf[26]),
    .Q(sum[26]),
    .QN(_057_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _251_ (
    .CK(clock),
    .D(sumf[27]),
    .Q(sum[27]),
    .QN(_058_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _252_ (
    .CK(clock),
    .D(sumf[28]),
    .Q(sum[28]),
    .QN(_059_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _253_ (
    .CK(clock),
    .D(sumf[29]),
    .Q(sum[29]),
    .QN(_060_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _254_ (
    .CK(clock),
    .D(sumf[30]),
    .Q(sum[30]),
    .QN(_061_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _255_ (
    .CK(clock),
    .D(sumf[31]),
    .Q(sum[31]),
    .QN(_062_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _256_ (
    .CK(clock),
    .D(sumf[32]),
    .Q(sum[32]),
    .QN(_063_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _257_ (
    .CK(clock),
    .D(sumf[33]),
    .Q(sum[33]),
    .QN(_064_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _258_ (
    .CK(clock),
    .D(sumf[34]),
    .Q(sum[34]),
    .QN(_065_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _259_ (
    .CK(clock),
    .D(sumf[35]),
    .Q(sum[35]),
    .QN(_066_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _260_ (
    .CK(clock),
    .D(sumf[36]),
    .Q(sum[36]),
    .QN(_067_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _261_ (
    .CK(clock),
    .D(sumf[37]),
    .Q(sum[37]),
    .QN(_068_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _262_ (
    .CK(clock),
    .D(sumf[38]),
    .Q(sum[38]),
    .QN(_069_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _263_ (
    .CK(clock),
    .D(sumf[39]),
    .Q(sum[39]),
    .QN(_070_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _264_ (
    .CK(clock),
    .D(sumf[40]),
    .Q(sum[40]),
    .QN(_071_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _265_ (
    .CK(clock),
    .D(sumf[41]),
    .Q(sum[41]),
    .QN(_072_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _266_ (
    .CK(clock),
    .D(sumf[42]),
    .Q(sum[42]),
    .QN(_073_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _267_ (
    .CK(clock),
    .D(sumf[43]),
    .Q(sum[43]),
    .QN(_074_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _268_ (
    .CK(clock),
    .D(sumf[44]),
    .Q(sum[44]),
    .QN(_075_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _269_ (
    .CK(clock),
    .D(sumf[45]),
    .Q(sum[45]),
    .QN(_076_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _270_ (
    .CK(clock),
    .D(sumf[46]),
    .Q(sum[46]),
    .QN(_077_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _271_ (
    .CK(clock),
    .D(sumf[47]),
    .Q(sum[47]),
    .QN(_078_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _272_ (
    .CK(clock),
    .D(sumf[48]),
    .Q(sum[48]),
    .QN(_079_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _273_ (
    .CK(clock),
    .D(sumf[49]),
    .Q(sum[49]),
    .QN(_080_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _274_ (
    .CK(clock),
    .D(sumf[50]),
    .Q(sum[50]),
    .QN(_081_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _275_ (
    .CK(clock),
    .D(sumf[51]),
    .Q(sum[51]),
    .QN(_082_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _276_ (
    .CK(clock),
    .D(sumf[52]),
    .Q(sum[52]),
    .QN(_083_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _277_ (
    .CK(clock),
    .D(sumf[53]),
    .Q(sum[53]),
    .QN(_084_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _278_ (
    .CK(clock),
    .D(sumf[54]),
    .Q(sum[54]),
    .QN(_085_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _279_ (
    .CK(clock),
    .D(sumf[55]),
    .Q(sum[55]),
    .QN(_086_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _280_ (
    .CK(clock),
    .D(sumf[56]),
    .Q(sum[56]),
    .QN(_087_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _281_ (
    .CK(clock),
    .D(sumf[57]),
    .Q(sum[57]),
    .QN(_088_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _282_ (
    .CK(clock),
    .D(sumf[58]),
    .Q(sum[58]),
    .QN(_089_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _283_ (
    .CK(clock),
    .D(sumf[59]),
    .Q(sum[59]),
    .QN(_090_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _284_ (
    .CK(clock),
    .D(sumf[60]),
    .Q(sum[60]),
    .QN(_091_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _285_ (
    .CK(clock),
    .D(sumf[61]),
    .Q(sum[61]),
    .QN(_092_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _286_ (
    .CK(clock),
    .D(sumf[62]),
    .Q(sum[62]),
    .QN(_093_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _287_ (
    .CK(clock),
    .D(sumf[63]),
    .Q(sum[63]),
    .QN(_094_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _288_ (
    .CK(clock),
    .D(op2[0]),
    .Q(b[0]),
    .QN(_095_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _289_ (
    .CK(clock),
    .D(op2[1]),
    .Q(b[1]),
    .QN(_096_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _290_ (
    .CK(clock),
    .D(op2[2]),
    .Q(b[2]),
    .QN(_097_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _291_ (
    .CK(clock),
    .D(op2[3]),
    .Q(b[3]),
    .QN(_098_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _292_ (
    .CK(clock),
    .D(op2[4]),
    .Q(b[4]),
    .QN(_099_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _293_ (
    .CK(clock),
    .D(op2[5]),
    .Q(b[5]),
    .QN(_100_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _294_ (
    .CK(clock),
    .D(op2[6]),
    .Q(b[6]),
    .QN(_101_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _295_ (
    .CK(clock),
    .D(op2[7]),
    .Q(b[7]),
    .QN(_102_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _296_ (
    .CK(clock),
    .D(op2[8]),
    .Q(b[8]),
    .QN(_103_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _297_ (
    .CK(clock),
    .D(op2[9]),
    .Q(b[9]),
    .QN(_104_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _298_ (
    .CK(clock),
    .D(op2[10]),
    .Q(b[10]),
    .QN(_105_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _299_ (
    .CK(clock),
    .D(op2[11]),
    .Q(b[11]),
    .QN(_106_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _300_ (
    .CK(clock),
    .D(op2[12]),
    .Q(b[12]),
    .QN(_107_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _301_ (
    .CK(clock),
    .D(op2[13]),
    .Q(b[13]),
    .QN(_108_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _302_ (
    .CK(clock),
    .D(op2[14]),
    .Q(b[14]),
    .QN(_109_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _303_ (
    .CK(clock),
    .D(op2[15]),
    .Q(b[15]),
    .QN(_110_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _304_ (
    .CK(clock),
    .D(op2[16]),
    .Q(b[16]),
    .QN(_111_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _305_ (
    .CK(clock),
    .D(op2[17]),
    .Q(b[17]),
    .QN(_112_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _306_ (
    .CK(clock),
    .D(op2[18]),
    .Q(b[18]),
    .QN(_113_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _307_ (
    .CK(clock),
    .D(op2[19]),
    .Q(b[19]),
    .QN(_114_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _308_ (
    .CK(clock),
    .D(op2[20]),
    .Q(b[20]),
    .QN(_115_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _309_ (
    .CK(clock),
    .D(op2[21]),
    .Q(b[21]),
    .QN(_116_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _310_ (
    .CK(clock),
    .D(op2[22]),
    .Q(b[22]),
    .QN(_117_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _311_ (
    .CK(clock),
    .D(op2[23]),
    .Q(b[23]),
    .QN(_118_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _312_ (
    .CK(clock),
    .D(op2[24]),
    .Q(b[24]),
    .QN(_119_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _313_ (
    .CK(clock),
    .D(op2[25]),
    .Q(b[25]),
    .QN(_120_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _314_ (
    .CK(clock),
    .D(op2[26]),
    .Q(b[26]),
    .QN(_121_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _315_ (
    .CK(clock),
    .D(op2[27]),
    .Q(b[27]),
    .QN(_122_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _316_ (
    .CK(clock),
    .D(op2[28]),
    .Q(b[28]),
    .QN(_123_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _317_ (
    .CK(clock),
    .D(op2[29]),
    .Q(b[29]),
    .QN(_124_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _318_ (
    .CK(clock),
    .D(op2[30]),
    .Q(b[30]),
    .QN(_125_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _319_ (
    .CK(clock),
    .D(op2[31]),
    .Q(b[31]),
    .QN(_126_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _320_ (
    .CK(clock),
    .D(op2[32]),
    .Q(b[32]),
    .QN(_127_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _321_ (
    .CK(clock),
    .D(op2[33]),
    .Q(b[33]),
    .QN(_128_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _322_ (
    .CK(clock),
    .D(op2[34]),
    .Q(b[34]),
    .QN(_129_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _323_ (
    .CK(clock),
    .D(op2[35]),
    .Q(b[35]),
    .QN(_130_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _324_ (
    .CK(clock),
    .D(op2[36]),
    .Q(b[36]),
    .QN(_131_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _325_ (
    .CK(clock),
    .D(op2[37]),
    .Q(b[37]),
    .QN(_132_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _326_ (
    .CK(clock),
    .D(op2[38]),
    .Q(b[38]),
    .QN(_133_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _327_ (
    .CK(clock),
    .D(op2[39]),
    .Q(b[39]),
    .QN(_134_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _328_ (
    .CK(clock),
    .D(op2[40]),
    .Q(b[40]),
    .QN(_135_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _329_ (
    .CK(clock),
    .D(op2[41]),
    .Q(b[41]),
    .QN(_136_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _330_ (
    .CK(clock),
    .D(op2[42]),
    .Q(b[42]),
    .QN(_137_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _331_ (
    .CK(clock),
    .D(op2[43]),
    .Q(b[43]),
    .QN(_138_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _332_ (
    .CK(clock),
    .D(op2[44]),
    .Q(b[44]),
    .QN(_139_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _333_ (
    .CK(clock),
    .D(op2[45]),
    .Q(b[45]),
    .QN(_140_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _334_ (
    .CK(clock),
    .D(op2[46]),
    .Q(b[46]),
    .QN(_141_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _335_ (
    .CK(clock),
    .D(op2[47]),
    .Q(b[47]),
    .QN(_142_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _336_ (
    .CK(clock),
    .D(op2[48]),
    .Q(b[48]),
    .QN(_143_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _337_ (
    .CK(clock),
    .D(op2[49]),
    .Q(b[49]),
    .QN(_144_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _338_ (
    .CK(clock),
    .D(op2[50]),
    .Q(b[50]),
    .QN(_145_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _339_ (
    .CK(clock),
    .D(op2[51]),
    .Q(b[51]),
    .QN(_146_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _340_ (
    .CK(clock),
    .D(op2[52]),
    .Q(b[52]),
    .QN(_147_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _341_ (
    .CK(clock),
    .D(op2[53]),
    .Q(b[53]),
    .QN(_148_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _342_ (
    .CK(clock),
    .D(op2[54]),
    .Q(b[54]),
    .QN(_149_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _343_ (
    .CK(clock),
    .D(op2[55]),
    .Q(b[55]),
    .QN(_150_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _344_ (
    .CK(clock),
    .D(op2[56]),
    .Q(b[56]),
    .QN(_151_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _345_ (
    .CK(clock),
    .D(op2[57]),
    .Q(b[57]),
    .QN(_152_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _346_ (
    .CK(clock),
    .D(op2[58]),
    .Q(b[58]),
    .QN(_153_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _347_ (
    .CK(clock),
    .D(op2[59]),
    .Q(b[59]),
    .QN(_154_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _348_ (
    .CK(clock),
    .D(op2[60]),
    .Q(b[60]),
    .QN(_155_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _349_ (
    .CK(clock),
    .D(op2[61]),
    .Q(b[61]),
    .QN(_156_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _350_ (
    .CK(clock),
    .D(op2[62]),
    .Q(b[62]),
    .QN(_157_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _351_ (
    .CK(clock),
    .D(op2[63]),
    .Q(b[63]),
    .QN(_158_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _352_ (
    .CK(clock),
    .D(coutf),
    .Q(crout),
    .QN(_159_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _353_ (
    .CK(clock),
    .D(op1[0]),
    .Q(a[0]),
    .QN(_160_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _354_ (
    .CK(clock),
    .D(op1[1]),
    .Q(a[1]),
    .QN(_161_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _355_ (
    .CK(clock),
    .D(op1[2]),
    .Q(a[2]),
    .QN(_162_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _356_ (
    .CK(clock),
    .D(op1[3]),
    .Q(a[3]),
    .QN(_163_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _357_ (
    .CK(clock),
    .D(op1[4]),
    .Q(a[4]),
    .QN(_164_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _358_ (
    .CK(clock),
    .D(op1[5]),
    .Q(a[5]),
    .QN(_165_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _359_ (
    .CK(clock),
    .D(op1[6]),
    .Q(a[6]),
    .QN(_166_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _360_ (
    .CK(clock),
    .D(op1[7]),
    .Q(a[7]),
    .QN(_167_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _361_ (
    .CK(clock),
    .D(op1[8]),
    .Q(a[8]),
    .QN(_168_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _362_ (
    .CK(clock),
    .D(op1[9]),
    .Q(a[9]),
    .QN(_169_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _363_ (
    .CK(clock),
    .D(op1[10]),
    .Q(a[10]),
    .QN(_170_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _364_ (
    .CK(clock),
    .D(op1[11]),
    .Q(a[11]),
    .QN(_171_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _365_ (
    .CK(clock),
    .D(op1[12]),
    .Q(a[12]),
    .QN(_172_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _366_ (
    .CK(clock),
    .D(op1[13]),
    .Q(a[13]),
    .QN(_173_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _367_ (
    .CK(clock),
    .D(op1[14]),
    .Q(a[14]),
    .QN(_174_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _368_ (
    .CK(clock),
    .D(op1[15]),
    .Q(a[15]),
    .QN(_175_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _369_ (
    .CK(clock),
    .D(op1[16]),
    .Q(a[16]),
    .QN(_176_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _370_ (
    .CK(clock),
    .D(op1[17]),
    .Q(a[17]),
    .QN(_177_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _371_ (
    .CK(clock),
    .D(op1[18]),
    .Q(a[18]),
    .QN(_178_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _372_ (
    .CK(clock),
    .D(op1[19]),
    .Q(a[19]),
    .QN(_179_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _373_ (
    .CK(clock),
    .D(op1[20]),
    .Q(a[20]),
    .QN(_180_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _374_ (
    .CK(clock),
    .D(op1[21]),
    .Q(a[21]),
    .QN(_181_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _375_ (
    .CK(clock),
    .D(op1[22]),
    .Q(a[22]),
    .QN(_182_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _376_ (
    .CK(clock),
    .D(op1[23]),
    .Q(a[23]),
    .QN(_183_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _377_ (
    .CK(clock),
    .D(op1[24]),
    .Q(a[24]),
    .QN(_184_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _378_ (
    .CK(clock),
    .D(op1[25]),
    .Q(a[25]),
    .QN(_185_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _379_ (
    .CK(clock),
    .D(op1[26]),
    .Q(a[26]),
    .QN(_186_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _380_ (
    .CK(clock),
    .D(op1[27]),
    .Q(a[27]),
    .QN(_187_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _381_ (
    .CK(clock),
    .D(op1[28]),
    .Q(a[28]),
    .QN(_188_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _382_ (
    .CK(clock),
    .D(op1[29]),
    .Q(a[29]),
    .QN(_189_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _383_ (
    .CK(clock),
    .D(op1[30]),
    .Q(a[30]),
    .QN(_190_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _384_ (
    .CK(clock),
    .D(op1[31]),
    .Q(a[31]),
    .QN(_191_),
    .RN(reset)
  );
  (* src = "rca_64bit.v:58" *)
  DFFR_X1 _385_ (
    .CK(clock),
    .D(op1[32]),
    .Q(a[32]),
    .QN(_192_),
    .RN(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:85" *)
  four_0bit fa1 (
    .a(a[3:0]),
    .b(b[3:0]),
    .cout4(r[0]),
    .sum4(sumf[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:94" *)
  four_1bit fa10 (
    .a(a[39:36]),
    .b(b[39:36]),
    .cin(r[8]),
    .cout3(r[9]),
    .sum3(sumf[39:36])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:95" *)
  four_1bit fa11 (
    .a(a[43:40]),
    .b(b[43:40]),
    .cin(r[9]),
    .cout3(r[10]),
    .sum3(sumf[43:40])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:96" *)
  four_1bit fa12 (
    .a(a[47:44]),
    .b(b[47:44]),
    .cin(r[10]),
    .cout3(r[11]),
    .sum3(sumf[47:44])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:97" *)
  four_1bit fa13 (
    .a(a[51:48]),
    .b(b[51:48]),
    .cin(r[11]),
    .cout3(r[12]),
    .sum3(sumf[51:48])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:98" *)
  four_1bit fa14 (
    .a(a[55:52]),
    .b(b[55:52]),
    .cin(r[12]),
    .cout3(r[13]),
    .sum3(sumf[55:52])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:99" *)
  four_1bit fa15 (
    .a(a[59:56]),
    .b(b[59:56]),
    .cin(r[13]),
    .cout3(r[14]),
    .sum3(sumf[59:56])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:100" *)
  four_1bit fa16 (
    .a(a[63:60]),
    .b(b[63:60]),
    .cin(r[14]),
    .cout3(coutf),
    .sum3(sumf[63:60])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:86" *)
  four_1bit fa2 (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(r[0]),
    .cout3(r[1]),
    .sum3(sumf[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:87" *)
  four_1bit fa3 (
    .a(a[11:8]),
    .b(b[11:8]),
    .cin(r[1]),
    .cout3(r[2]),
    .sum3(sumf[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:88" *)
  four_1bit fa4 (
    .a(a[15:12]),
    .b(b[15:12]),
    .cin(r[2]),
    .cout3(r[3]),
    .sum3(sumf[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:89" *)
  four_1bit fa5 (
    .a(a[19:16]),
    .b(b[19:16]),
    .cin(r[3]),
    .cout3(r[4]),
    .sum3(sumf[19:16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:90" *)
  four_1bit fa6 (
    .a(a[23:20]),
    .b(b[23:20]),
    .cin(r[4]),
    .cout3(r[5]),
    .sum3(sumf[23:20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:91" *)
  four_1bit fa7 (
    .a(a[27:24]),
    .b(b[27:24]),
    .cin(r[5]),
    .cout3(r[6]),
    .sum3(sumf[27:24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:92" *)
  four_1bit fa8 (
    .a(a[31:28]),
    .b(b[31:28]),
    .cin(r[6]),
    .cout3(r[7]),
    .sum3(sumf[31:28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca_64bit.v:93" *)
  four_1bit fa9 (
    .a(a[35:32]),
    .b(b[35:32]),
    .cin(r[7]),
    .cout3(r[8]),
    .sum3(sumf[35:32])
  );
endmodule
